### ISSUE TITLE
TypeError: Cannot read property 'ignorePartialSupport' of undefined

### ISSUE THREAD

**Issue by ybiquitous** [ismay/stylelint-no-unsupported-browser-features#109]
Hello. When I try the latest version [4.1.1](https://github.com/ismay/stylelint-no-unsupported-browser-features/releases/tag/v4.1.1), the following error occurs:

```
TypeError: Cannot read property 'ignorePartialSupport' of undefined
    at /private/tmp/repro/node_modules/stylelint-no-unsupported-browser-features/lib/index.js:84:17
    at Array.forEach (<anonymous>)
    at /private/tmp/repro/node_modules/stylelint-no-unsupported-browser-features/lib/index.js:82:29
    at /private/tmp/repro/node_modules/stylelint/lib/lintPostcssResult.js:118:8
    at Array.map (<anonymous>)
    at /private/tmp/repro/node_modules/stylelint/lib/lintPostcssResult.js:110:18
    at Array.forEach (<anonymous>)
    at lintPostcssResult (/private/tmp/repro/node_modules/stylelint/lib/lintPostcssResult.js:74:8)
    at /private/tmp/repro/node_modules/stylelint/lib/lintSource.js:101:13
    at async Promise.all (index 0)
```

## Reproduction

Given files:

```css
/* a.css */
a {
  filter: brightness(110%);
}
```

```
# .browserslistrc
last 2 versions
```

```json5
// package.json
{
  "dependencies": {
    "stylelint": "^13.7.2",
    "stylelint-no-unsupported-browser-features": "^4.1.1"
  }
}
```

Run:

```console
$ node_modules/.bin/stylelint a.css
TypeError: Cannot read property 'ignorePartialSupport' of undefined
    at /private/tmp/repro/node_modules/stylelint-no-unsupported-browser-features/lib/index.js:84:17
    at Array.forEach (<anonymous>)
    at /private/tmp/repro/node_modules/stylelint-no-unsupported-browser-features/lib/index.js:82:29
    at /private/tmp/repro/node_modules/stylelint/lib/lintPostcssResult.js:118:8
    at Array.map (<anonymous>)
    at /private/tmp/repro/node_modules/stylelint/lib/lintPostcssResult.js:110:18
    at Array.forEach (<anonymous>)
    at lintPostcssResult (/private/tmp/repro/node_modules/stylelint/lib/lintPostcssResult.js:74:8)
    at /private/tmp/repro/node_modules/stylelint/lib/lintSource.js:101:13
    at async Promise.all (index 0)
```

I would be happy if you could confirm it.

**Comment by ismay** [comment]
You're right, my bad, I'll publish a fix. Thanks for reporting!

**Comment by ismay** [comment]
I'll publish a fix today, but am also improving the test suite while I'm at it. In the meantime, you can suppress this error by passing an empty object in this rule's config:

```
{
  "plugins": [
    "stylelint-no-unsupported-browser-features"
  ],
  "rules": {
    "plugin/no-unsupported-browser-features": [true, {}]
  }
}
```

Just for the meantime, in case this is blocking anything. But as said, I'll publish the fix asap.

**Comment by ismay** [comment]
Should be resolved with 4.1.2. Let me know if this fixes it for you!

**Comment by ybiquitous** [comment]
Thank you so much! I could confirm v4.1.2 works! 😊

**Comment by ismay** [comment]
Nice. You're welcome 👍! Thanks for reporting the issue.
